version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080" # API & WS
      - "3000:3000" # P2P
    volumes:
      - ./data/backend:/data
    environment:
      - P2P_PORT=3000
      - API_PORT=8080
      - PRIVATE_KEY=${PRIVATE_KEY:-c0c237c395fa01d975651c346995e378ab199cc1b40c6dbb353fad9363c2d621}
      - BOOTSTRAP_PEERS=${BOOTSTRAP_PEERS}
    restart: unless-stopped
    networks:
      - bery-net

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - bery-net

networks:
  bery-net:
    driver: bridge
